pessoas = {'nome': 'Erik', 'sexo': 'M', 'idade': 21}
print(pessoas)
# print(pessoas[0])
print(pessoas['nome'])
print(pessoas['idade'])
print(f'O {pessoas["nome"]} tem {pessoas["idade"]} anos.')
print('-=' * 10)
print(pessoas.keys())
print('-=' * 10)
print(pessoas.values())
print('-=' * 10)
print(pessoas.items())
print('-=' * 10)
