# PECULIARIDADE DO PYTHON
a = [2, 3, 4, 7]
b = a # IGUALANDO LISTAS
# A PARTIR DO MOMENTO QUE EU IGUALO AS LISTAS O PYTHON LIGA UMA LIGAÇÃO ENTRE ELAS
b[2] = 8
print(f'Lista A: {a}')
print(f'Lista B: {b}')
